# 配置文件加密key
jasypt:
  encryptor:
    password: root

spring:
  # 数据源
  datasource:
    url: jdbc:mysql://118.123.16.211:3306/shentu?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    # Jasypt加密 可到common-utils中找到 JasyptUtil 加解密工具类生成加密结果 格式为ENC(加密结果)
    password: ENC(B6M4HhIardKWsVvF2xyTyR8lReyEBFeU)
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    logSlowSql: true

